models:
  - name: stg_fhv_tripdata
    description: >
      Staging model for FHV trip data. This model standardizes column names
    columns:
      - name: dispatching_base_num
        description: The TLC Base License Number of the base that dispatched the trip.
        data_tests:
          - not_null
      - name: pickup_datetime
        description: The date and time of the trip pick-up.
        data_tests:
          - not_null
      - name: dropoff_datetime
        description: The date and time of the trip drop-off.
      - name: pickup_location_id
        description: TLC Taxi Zone where the meter was engaged
      - name: dropoff_location_id
        description: TLC Taxi Zone where the meter was disengaged
      - name: sr_flag
        description: |
          Indicates if the trip was a part of a shared ride chain offered by a High
          Volume FHV company (e.g. Uber Pool, Lyft Line). For shared trips, the value
          is 1. For non-shared rides, this field is 0 (originally null).
          NOTE: For most High Volume FHV companies, only shared rides that were
          requested AND matched to another shared-ride request over the course of
          the journey are flagged. However, Lyft (base license numbers B02510 +
          B02844) also flags rides for which a shared ride was requested but another
          passenger was not successfully matched to share the trip—therefore, trips
          records with SR_Flag=1 from those two bases could indicate EITHER a first
          trip in a shared trip chain OR a trip for which a shared ride was requested but
          never matched. Users should anticipate an overcount of successfully shared
          trips completed by Lyft. 
      - name: affiliated_base_number
        description: |
          Base number of the base with which the vehicle is affiliated. This
          must be provided even if the affiliated base is the same as the
          dispatching base.

      
  - name: stg_green_tripdata
    description: >
      Staging model for green taxi trip data. This model standardizes column names
      and data types from the raw green_tripdata source, providing a clean foundation
      for downstream transformations.
    columns:
      - name: vendor_id
        description: Taxi technology provider (1 = Creative Mobile Technologies, 2 = VeriFone Inc.)
        data_tests:
          - not_null
      - name: rate_code_id
        description: Rate code at end of trip (1=Standard, 2=JFK, 3=Newark, 4=Nassau/Westchester, 5=Negotiated, 6=Group)
      - name: pickup_location_id
        description: TLC Taxi Zone where the meter was engaged
      - name: dropoff_location_id
        description: TLC Taxi Zone where the meter was disengaged
      - name: pickup_datetime
        description: Date and time when the meter was engaged
        data_tests:
          - not_null
      - name: dropoff_datetime
        description: Date and time when the meter was disengaged
      - name: store_and_fwd_flag
        description: Flag indicating if trip record was held in vehicle memory (Y/N)
      - name: passenger_count
        description: Number of passengers in the vehicle (driver-entered value)
      - name: trip_distance
        description: Trip distance in miles reported by the taximeter
      - name: trip_type
        description: Code for trip type (1=Street-hail, 2=Dispatch)
      - name: fare_amount
        description: Time and distance fare calculated by the meter
      - name: extra
        description: Miscellaneous extras and surcharges (rush hour, overnight)
      - name: mta_tax
        description: $0.50 MTA tax automatically triggered based on meter rate
      - name: tip_amount
        description: Tip amount (credit card tips only, cash tips not included)
      - name: tolls_amount
        description: Total amount of all tolls paid during the trip
      - name: ehail_fee
        description: E-hail service fee
      - name: improvement_surcharge
        description: Improvement surcharge assessed on hailed trips
      - name: total_amount
        description: Total amount charged to passengers (does not include cash tips)
      - name: payment_type
        description: Payment method code (1=Credit card, 2=Cash, 3=No charge, 4=Dispute, 5=Unknown, 6=Voided)

  - name: stg_yellow_tripdata
    description: >
      Staging model for yellow taxi trip data. This model standardizes column names
      and data types from the raw yellow_tripdata source, providing a clean foundation
      for downstream transformations.
    columns:
      - name: vendor_id
        description: Taxi technology provider (1 = Creative Mobile Technologies, 2 = VeriFone Inc.)
        data_tests:
          - not_null
      - name: rate_code_id
        description: Rate code at end of trip (1=Standard, 2=JFK, 3=Newark, 4=Nassau/Westchester, 5=Negotiated, 6=Group)
      - name: pickup_location_id
        description: TLC Taxi Zone where the meter was engaged
      - name: dropoff_location_id
        description: TLC Taxi Zone where the meter was disengaged
      - name: pickup_datetime
        description: Date and time when the meter was engaged
        data_tests:
          - not_null
      - name: dropoff_datetime
        description: Date and time when the meter was disengaged
      - name: store_and_fwd_flag
        description: Flag indicating if trip record was held in vehicle memory (Y/N)
      - name: passenger_count
        description: Number of passengers in the vehicle (driver-entered value)
      - name: trip_distance
        description: Trip distance in miles reported by the taximeter
      - name: fare_amount
        description: Time and distance fare calculated by the meter
      - name: extra
        description: Miscellaneous extras and surcharges (rush hour, overnight)
      - name: mta_tax
        description: $0.50 MTA tax automatically triggered based on meter rate
      - name: tip_amount
        description: Tip amount (credit card tips only, cash tips not included)
      - name: tolls_amount
        description: Total amount of all tolls paid during the trip
      - name: improvement_surcharge
        description: Improvement surcharge assessed on hailed trips
      - name: total_amount
        description: Total amount charged to passengers (does not include cash tips)
      - name: payment_type
        description: Payment method code (1=Credit card, 2=Cash, 3=No charge, 4=Dispute, 5=Unknown, 6=Voided)